---
openapi: 3.0.0
info:
  title: Stats API
  description: This API provides event stats
  contact:
    email: stevennguyen901@gmail.com
  version: 1.0.0

paths:
  /stats:
    get:
      summary: Gets event stats
      description: Gets orders and deliveries processed statistics
      operationId: app.get_stats
      responses:
        "200":  
          description: Successfully return list of processed statistics
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/AppStats'
        "400":
          description: invalid input, object invalid

components:
  schemas:
    AppStats:
      required:
      - windows_percent
      - mac_percent
      type: object
      properties:
        windows_percent:
          type: integer
          example: 12345
        mac_percent:
          type: integer
          example: 54321
